import { sql } from "kysely";
import type { Migration } from "kysely/migration";

export const up: Migration["up"] = async (db) => {
  await sql`
    CREATE TABLE users (
      id uuid PRIMARY KEY,
      external_id text UNIQUE,
      email text NOT NULL UNIQUE,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `.execute(db);

  await sql`
    CREATE TABLE sessions (
      sid uuid PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at timestamptz NOT NULL,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `.execute(db);

  await sql`
    CREATE TABLE recipes (
      id uuid PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      parent_id uuid REFERENCES recipes(id) ON DELETE SET NULL,
      title text NOT NULL CHECK (char_length(btrim(title)) BETWEEN 1 AND 150),
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `.execute(db);

  await sql`
    CREATE TABLE recipe_versions (
      id uuid PRIMARY KEY,
      recipe_id uuid NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
      version_number integer NOT NULL CHECK (version_number > 0),
      description text,
      servings integer CHECK (servings IS NULL OR servings > 0),
      total_time integer CHECK (total_time IS NULL OR total_time > 0),
      calories integer CHECK (calories IS NULL OR calories >= 0),
      source_type text CHECK (source_type IN ('url', 'instruction', 'raw_text')),
      source_value text,
      source_summary text,
      ai_model text,
      relation text NOT NULL DEFAULT 'reply' CHECK (relation IN ('reply', 'fork')),
      notes text,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (recipe_id, version_number)
    )
  `.execute(db);

  await sql`
    CREATE TABLE recipe_version_ingredients (
      id uuid PRIMARY KEY,
      recipe_version_id uuid NOT NULL REFERENCES recipe_versions(id) ON DELETE CASCADE,
      position integer NOT NULL CHECK (position > 0),
      raw_text text NOT NULL CHECK (char_length(btrim(raw_text)) > 0),
      ingredient_name text NOT NULL CHECK (char_length(btrim(ingredient_name)) > 0),
      quantity_value double precision,
      quantity_text text,
      unit text,
      alternate_quantity_value double precision,
      alternate_quantity_text text,
      alternate_unit text,
      note text,
      is_optional boolean NOT NULL DEFAULT false,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (recipe_version_id, position)
    )
  `.execute(db);

  await sql`
    CREATE TABLE recipe_version_steps (
      id uuid PRIMARY KEY,
      recipe_version_id uuid NOT NULL REFERENCES recipe_versions(id) ON DELETE CASCADE,
      position integer NOT NULL CHECK (position > 0),
      raw_text text NOT NULL CHECK (char_length(btrim(raw_text)) > 0),
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE (recipe_version_id, position)
    )
  `.execute(db);

  await sql`
    CREATE TABLE tags (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name text NOT NULL CHECK (char_length(btrim(name)) > 0),
      color text NOT NULL DEFAULT '#FFB86C' CHECK (char_length(btrim(color)) > 0),
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `.execute(db);

  await sql`CREATE UNIQUE INDEX uq_tags_user_normalized_name ON tags(user_id, lower(btrim(name)))`.execute(
    db,
  );

  await sql`
    CREATE TABLE recipe_tags (
      recipe_id uuid NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
      tag_id integer NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (recipe_id, tag_id)
    )
  `.execute(db);

  await sql`
    CREATE TABLE messages (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
      recipe_version_id uuid REFERENCES recipe_versions(id) ON DELETE SET NULL,
      role text NOT NULL CHECK (role IN ('user', 'assistant')),
      content text NOT NULL CHECK (char_length(btrim(content)) > 0),
      status text,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `.execute(db);

  await sql`
    CREATE TABLE url_cache (
      normalized_url text PRIMARY KEY,
      source_url text NOT NULL,
      content text NOT NULL,
      fetched_at timestamptz NOT NULL,
      expires_at timestamptz NOT NULL,
      created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `.execute(db);

  await sql`CREATE INDEX idx_sessions_user_id ON sessions(user_id)`.execute(db);
  await sql`CREATE INDEX idx_sessions_expires_at ON sessions(expires_at)`.execute(
    db,
  );
  await sql`CREATE INDEX idx_recipes_user_id_created_at ON recipes(user_id, created_at DESC)`.execute(
    db,
  );
  await sql`CREATE INDEX idx_tags_user_id ON tags(user_id)`.execute(db);
  await sql`CREATE INDEX idx_recipe_tags_tag_id ON recipe_tags(tag_id)`.execute(
    db,
  );
  await sql`CREATE INDEX idx_messages_recipe_id_created_at ON messages(recipe_id, created_at DESC)`.execute(
    db,
  );
  await sql`CREATE INDEX idx_messages_recipe_version_id_created_at ON messages(recipe_version_id, created_at DESC)`.execute(
    db,
  );
};

export const down: Migration["down"] = async (db) => {
  await sql`DROP TABLE IF EXISTS messages`.execute(db);
  await sql`DROP TABLE IF EXISTS recipe_tags`.execute(db);
  await sql`DROP TABLE IF EXISTS tags`.execute(db);
  await sql`DROP TABLE IF EXISTS recipe_version_steps`.execute(db);
  await sql`DROP TABLE IF EXISTS recipe_version_ingredients`.execute(db);
  await sql`DROP TABLE IF EXISTS recipe_versions`.execute(db);
  await sql`DROP TABLE IF EXISTS recipes`.execute(db);
  await sql`DROP TABLE IF EXISTS sessions`.execute(db);
  await sql`DROP TABLE IF EXISTS url_cache`.execute(db);
  await sql`DROP TABLE IF EXISTS users`.execute(db);
};
